### ISSUE TITLE
希望支持共享订阅 [QUESTION]

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [simps/mqtt#101]
我想用共享订阅  主题是 $queue/Server/Data/#   
我在示例里面没找到用法 我直接订阅上面的主题返回true但是没有订阅上

**Comment by sy-records** [comment]
一样的，订阅成功不成功需要看 server

**Comment by ZhangTianyi-1998** [comment]
emqx的后台看不到订阅 客户端接收不到消息  我是这么写的 您看对么
![image](https://github.com/user-attachments/assets/2a9a61a0-d251-4f79-9adb-1e25ee3c3d51)

**Comment by sy-records** [comment]
<img width="1485" alt="image" src="https://github.com/user-attachments/assets/46a74eee-5d05-4aff-943c-bd89eaad4fd5">

**Comment by ZhangTianyi-1998** [comment]
这个不是共享订阅呀   共享订阅的topic是这样的 $queue/simps-mqtt/users/002

**Comment by sy-records** [comment]
有没有可能是一样的？

<img width="763" alt="image" src="https://github.com/user-attachments/assets/a552f08c-0a89-45a8-a5e9-0e41c325e8b6">

https://www.emqx.com/zh/blog/introduction-to-mqtt5-protocol-shared-subscription
