### ISSUE TITLE
[QUESTION]捐款受挫。

### ISSUE THREAD

**Issue by gzqy** [simps/mqtt#104]
我尝试捐款，但是捐款要我实名认证。本来想捐一点支持一下，但是实名就很烦。放弃了。   你下次直接放链接吧。扫码直接捐那种。

**Comment by sy-records** [comment]
谢谢❤️

微信支付宝扫这里 https://donate.qq52o.me

**Comment by gzqy** [comment]
不行啊






1352411768
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "simps/mqtt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月13日(星期五) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [simps/mqtt] [QUESTION]捐款受挫。 (Issue #104)





 
谢谢❤️
 
微信支付宝扫这里 https://donate.qq52o.me

**Comment by sy-records** [comment]
![image](https://github.com/user-attachments/assets/a42752a0-dbff-45f5-abc0-70c0af23c4a2)

**Comment by gzqy** [comment]
好了、
&nbsp;


1352411768
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月13日(星期五) 下午2:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [simps/mqtt] [QUESTION]捐款受挫。 (Issue #104)














 
C853804D-DAB1-439A-9D06-08129C060DDE.png (view on web)

**Comment by sy-records** [comment]
谢谢
