### ISSUE TITLE
[QUESTION] Installation failed

### ISSUE THREAD

**Issue by ninora** [simps/mqtt#23]
Not sure what is the problem:

`composer require simps/mqtt
Do not run Composer as root/super user! See https://getcomposer.org/root for det                            ails
Continue as root/super user [yes]? y
Using version ^1.1 for simps/mqtt
./composer.json has been created
Running composer update simps/mqtt
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - simps/mqtt[v1.1.0, ..., v1.1.2] require ext-swoole >=4.4.19 -> it is missing from your system. Install or enable PHP's swoole extension.
    - Root composer.json requires simps/mqtt ^1.1 -> satisfiable by simps/mqtt[v                            1.1.0, v1.1.1, v1.1.2].

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php8.0-sp/php.ini
    - /etc/php8.0-sp/conf.d/bcmath.ini
    - /etc/php8.0-sp/conf.d/bz2.ini
    - /etc/php8.0-sp/conf.d/curl.ini
    - /etc/php8.0-sp/conf.d/exif.ini
    - /etc/php8.0-sp/conf.d/gd.ini
    - /etc/php8.0-sp/conf.d/gettext.ini
    - /etc/php8.0-sp/conf.d/gmp.ini
    - /etc/php8.0-sp/conf.d/imap.ini
    - /etc/php8.0-sp/conf.d/intl.ini
    - /etc/php8.0-sp/conf.d/ldap.ini
    - /etc/php8.0-sp/conf.d/mbstring.ini
    - /etc/php8.0-sp/conf.d/mysqli.ini
    - /etc/php8.0-sp/conf.d/odbc.ini
    - /etc/php8.0-sp/conf.d/opcache.ini
    - /etc/php8.0-sp/conf.d/pcntl.ini
    - /etc/php8.0-sp/conf.d/pdo_dblib.ini
    - /etc/php8.0-sp/conf.d/pdo_mysql.ini
    - /etc/php8.0-sp/conf.d/pdo_odbc.ini
    - /etc/php8.0-sp/conf.d/pdo_pgsql.ini
    - /etc/php8.0-sp/conf.d/pdo_sqlite.ini
    - /etc/php8.0-sp/conf.d/pgsql.ini
    - /etc/php8.0-sp/conf.d/shmop.ini
    - /etc/php8.0-sp/conf.d/tidy.ini
    - /etc/php8.0-sp/conf.d/xsl.ini
You can also run `php --ini` inside terminal to see which files are used by PHP                             in CLI mode.

Installation failed, deleting ./composer.json.`

**Comment by sy-records** [comment]
You didn't install the swoole extension. https://github.com/swoole/swoole-src

**Comment by ninora** [comment]
Thanks
