### ISSUE TITLE
[BUG]无论publish的qos级别是多少，订阅到的结果都是qos=0

### ISSUE THREAD

**Issue by captainnx** [simps/mqtt#50]
Array
(
    [type] => 3
    [dup] => 0
    [qos] => 0
    [retain] => 0
    [topic] => 
    [properties] => Array
        (
            [topic_alias] => 1
        )

    [message] => "captain"
)

**Comment by sy-records** [comment]
请按照issue模板提问。

**Comment by sy-records** [comment]
![image](https://user-images.githubusercontent.com/33931153/116346747-6e1f6000-a81d-11eb-944c-b8beebbfa6ae.png)

**Comment by captainnx** [comment]
![image](https://user-images.githubusercontent.com/31986362/116348375-978dbb00-a820-11eb-9f71-95da9cffd1a0.png)

**Comment by sy-records** [comment]
贴代码，按模板提问...

**Comment by captainnx** [comment]
好了，谢谢，当订阅为0时，无论发布的qos级别为多少都会打印0，把订阅改成2后没问题了
