### ISSUE TITLE
Uncaught Error: Call to undefined function Swoole\Coroutine\run()

### ISSUE THREAD

**Issue by cshitian** [simps/mqtt#76]
运行后 报这个错误

**Comment by cshitian** [comment]
是需要安装什么吗？  宝塔面板的

**Comment by sy-records** [comment]
需要安装Swoole。大于 v4.4 版本

**Comment by cshitian** [comment]
![image](https://user-images.githubusercontent.com/24708632/153985079-87a0ff19-43a9-42f8-ba59-891de67f3cb7.png)
yi'j已经安装了 还是不行

**Comment by sy-records** [comment]
你怎么运行的代码？什么代码？

```bash
php --ri swoole
```

**Comment by cshitian** [comment]
宝塔面板问题 。。。。。  有没有啥项目 能直接测试跑的？  或者php的例子

**Comment by sy-records** [comment]
https://github.com/simps/mqtt/tree/master/examples

**Comment by cshitian** [comment]
呃  高出了我的能力。  我搜搜看看有没有别人 写得比较简单的
