### ISSUE TITLE
使用阿里云MQTT微消息队列发送消息时报错

### ISSUE THREAD

**Issue by 250121244** [simps/mqtt#9]
场景:
点对点模式推送消息.

错误提示如下:
PHP Notice:  Uninitialized string offset: 0 in /var/www/hhd_api/vendor/simps/mqtt/src/Packet/UnPackV5.php on line 369

Notice: Uninitialized string offset: 0 in /var/www/hhd_api/vendor/simps/mqtt/src/Packet/UnPackV5.php on line 369
array(4) {
  ["type"]=>
  int(5)
  ["message_id"]=>
  int(1)
  ["code"]=>
  int(128)
  ["message"]=>
  string(17) "Unspecified error"
}

**Comment by 250121244** [comment]
从配置文件来看, 应该是还不支持吧.  目前是只支持自建MQTT服务器的模式吗

**Comment by sy-records** [comment]
支持MQTT标准协议，没测试阿里云的兼容性，可以给个复现代码我看看

**Comment by sy-records** [comment]
我用阿里云发布订阅测试了下，这个需要找下阿里云，Publish Ack返回的就是这个，但是又算成功了，订阅端还能收到publish

![image](https://user-images.githubusercontent.com/33931153/102315167-a8930980-3fae-11eb-9b13-4731af3b11a6.png)

**Comment by sy-records** [comment]
使用3.1.1版本吧。

![image](https://user-images.githubusercontent.com/33931153/102323239-31b03d80-3fbb-11eb-98ee-2a1fc4bfffd8.png)
