### ISSUE TITLE
[QUESTION]send方法中response默认值为true,当用协程去处理recv消息时会跟simps中的协程冲突导致报错

### ISSUE THREAD

**Issue by summers8** [simps/mqtt#91]
Fatal error: Uncaught Swoole\Error: Socket#8 has already been bound to another coroutine#2, reading of the same socket in coroutine#1 at the same time is not allowed in /www/swooleroot/admin-api/vendor/simps/mqtt/src/Client.php:242
使用的simps版本为：V1.4.2
![image](https://github.com/simps/mqtt/assets/18204170/4cc73575-b8de-482c-ae4e-3090b3e6e58a)

**Comment by sy-records** [comment]
可以配合 https://github.com/hyperf/multiplex 增加channel使用
