### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vssir** [simps/mqtt#92]
这个异常问题出现的概率还是有点高。
![image](https://github.com/simps/mqtt/assets/10388068/321fc3fa-c8a8-4563-8945-eb5359134b6c)
unpack 函数输入字符串长度至少2位或以上，当少于2位就会报错。

**Comment by sy-records** [comment]
用debug工具把包打出来看下，你这个可能是数据格式的问题，或者协议等级不是v3
