### ISSUE TITLE
[QUESTION]已设置clean_session=false，但重连后依然没有订阅原有的主题

### ISSUE THREAD

**Issue by hs19940808** [simps/mqtt#95]
框架：hyperf3.0
simps/mqtt：1.4，
EMQX版本：4.3.22

已设置clean_session=false，但重连后依然没有订阅原有的主题

![image](https://github.com/simps/mqtt/assets/34149339/12b4da7f-a502-4ad6-89f6-c739fe9564eb)

首次连接：
![image](https://github.com/simps/mqtt/assets/34149339/3b9ab1c1-442f-4394-93d2-c74a642a8845)

踢出后重连：
![image](https://github.com/simps/mqtt/assets/34149339/d89bebde-b99b-459e-965c-5bf24a7dc437)

**Comment by sy-records** [comment]
需要自己处理一下重连。

see https://github.com/simps/mqtt/issues/90#issuecomment-1512703525

**Comment by 898601566** [comment]
> 框架：hyperf3.0 simps/mqtt：1.4， EMQX版本：4.3.22
> 
> 已设置clean_session=false，但重连后依然没有订阅原有的主题
> 
> ![image](https://github.com/simps/mqtt/assets/34149339/12b4da7f-a502-4ad6-89f6-c739fe9564eb)
> 
> 首次连接： ![image](https://github.com/simps/mqtt/assets/34149339/3b9ab1c1-442f-4394-93d2-c74a642a8845)
> 
> 踢出后重连： ![image](https://github.com/simps/mqtt/assets/34149339/d89bebde-b99b-459e-965c-5bf24a7dc437)

因为作者没做连接钩子,我现在采用的方案是ping的时候再订阅一遍
