### ISSUE TITLE
[QUESTION]recv方法可以设置停止接收的时间吗

### ISSUE THREAD

**Issue by hs19940808** [simps/mqtt#97]
有一个需求是在3s内监听一个topic，如果没收到消息则执行其他操作，使用recv就阻塞了进程，无法判断时间了

**Comment by sy-records** [comment]
使用Swoole的配置，设置超时时间。

https://github.com/simps/mqtt/blob/6c489e123bf2d50be309cae8bd7f0bdc55311489/examples/bootstrap.php#L34-L36
